/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package funciones;
import datos1.*;
import paneles.*;
/**
 *
 * @author Usuario
 */
public class OpcionLibro1 extends javax.swing.JInternalFrame {
    private Biblioteca biblioteca;
    /**
     * Creates new form OpcionLibro1
     */
    public OpcionLibro1(Biblioteca p_biblio) {
        biblioteca = p_biblio;
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void refrescarQuitar(){
        new CambiaPanel(fondo, new QuitarLibro(biblioteca));
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbAgregarLibro = new javax.swing.JButton();
        jbQuitarLibro = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setLayout(new javax.swing.BoxLayout(fondo, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbAgregarLibro.setBackground(new java.awt.Color(250, 250, 250));
        jbAgregarLibro.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jbAgregarLibro.setForeground(new java.awt.Color(239, 60, 78));
        jbAgregarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/QuitarLibro.png"))); // NOI18N
        jbAgregarLibro.setBorder(null);
        jbAgregarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbAgregarLibro.setFocusPainted(false);
        jbAgregarLibro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbAgregarLibro.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jbAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarLibroActionPerformed(evt);
            }
        });
        jPanel2.add(jbAgregarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 180, 130));

        jbQuitarLibro.setBackground(new java.awt.Color(250, 250, 250));
        jbQuitarLibro.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jbQuitarLibro.setForeground(new java.awt.Color(239, 60, 78));
        jbQuitarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AñadirLibro.png"))); // NOI18N
        jbQuitarLibro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 60, 78)));
        jbQuitarLibro.setContentAreaFilled(false);
        jbQuitarLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbQuitarLibro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbQuitarLibro.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jbQuitarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuitarLibroActionPerformed(evt);
            }
        });
        jPanel2.add(jbQuitarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 180, 130));

        jPanel8.setBackground(new java.awt.Color(239, 60, 78));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Decker", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Seleccione una opción:");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 314, -1));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 50));

        fondo.add(jPanel2);

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarLibroActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(fondo, new QuitarLibro(biblioteca));
    }//GEN-LAST:event_jbAgregarLibroActionPerformed

    private void jbQuitarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuitarLibroActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(fondo, new AgregarLibro(biblioteca));
    }//GEN-LAST:event_jbQuitarLibroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton jbAgregarLibro;
    private javax.swing.JButton jbQuitarLibro;
    // End of variables declaration//GEN-END:variables
}
