/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;
import funciones.OpcionSocio1;
import paneles.CambiaPanel;
import funciones.Inicio1;
import funciones.OpcionLibro1;
import datos1.Biblioteca;
import funciones.OpcionListar;
import funciones.OpcionPrestar;

/**
 *
 * @author Usuario
 */
public class Principal extends javax.swing.JFrame {

    private Biblioteca biblioteca;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();  
        this.setLocationRelativeTo(null);
        
        biblioteca= new Biblioteca("Biblioteca");
        
        Inicio1 inicio= new Inicio1(biblioteca);
        int width= jpPrincipal.getWidth();
        int height= jpPrincipal.getHeight();
        inicio.setSize(width, height);
        jpPrincipal.add(inicio);
        inicio.show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        rSButtonIconI1 = new rojerusan.RSButtonIconI();
        rSButtonIconI2 = new rojerusan.RSButtonIconI();
        rSButtonIconI3 = new rojerusan.RSButtonIconI();
        rSButtonIconI4 = new rojerusan.RSButtonIconI();
        rSButtonIconI6 = new rojerusan.RSButtonIconI();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jpPrincipal = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(197, 30, 46));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Decker", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Biblioteca Digital");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 190, 45));

        jSeparator1.setBackground(new java.awt.Color(240, 240, 240));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 190, 20));

        rSButtonIconI1.setBackground(new java.awt.Color(197, 30, 46));
        rSButtonIconI1.setForeground(new java.awt.Color(240, 240, 240));
        rSButtonIconI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_meeting_room_filled_80px.png"))); // NOI18N
        rSButtonIconI1.setText(" Socios               ");
        rSButtonIconI1.setBorderPainted(false);
        rSButtonIconI1.setColorHover(new java.awt.Color(176, 23, 37));
        rSButtonIconI1.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        rSButtonIconI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI1ActionPerformed(evt);
            }
        });
        jPanel5.add(rSButtonIconI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 250, 40));

        rSButtonIconI2.setBackground(new java.awt.Color(197, 30, 46));
        rSButtonIconI2.setForeground(new java.awt.Color(240, 240, 240));
        rSButtonIconI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_books_80px_1.png"))); // NOI18N
        rSButtonIconI2.setText("Libros                ");
        rSButtonIconI2.setBorderPainted(false);
        rSButtonIconI2.setColorHover(new java.awt.Color(176, 23, 37));
        rSButtonIconI2.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        rSButtonIconI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI2ActionPerformed(evt);
            }
        });
        jPanel5.add(rSButtonIconI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 250, 40));

        rSButtonIconI3.setBackground(new java.awt.Color(197, 30, 46));
        rSButtonIconI3.setForeground(new java.awt.Color(240, 240, 240));
        rSButtonIconI3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_show_password_filled_80px.png"))); // NOI18N
        rSButtonIconI3.setText("Listar                 ");
        rSButtonIconI3.setBorderPainted(false);
        rSButtonIconI3.setColorHover(new java.awt.Color(176, 23, 37));
        rSButtonIconI3.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        rSButtonIconI3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI3ActionPerformed(evt);
            }
        });
        jPanel5.add(rSButtonIconI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 250, 40));

        rSButtonIconI4.setBackground(new java.awt.Color(197, 30, 46));
        rSButtonIconI4.setForeground(new java.awt.Color(240, 240, 240));
        rSButtonIconI4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_reading_filled_80px.png"))); // NOI18N
        rSButtonIconI4.setText("Prestamo             ");
        rSButtonIconI4.setBorderPainted(false);
        rSButtonIconI4.setColorHover(new java.awt.Color(176, 23, 37));
        rSButtonIconI4.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        rSButtonIconI4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI4ActionPerformed(evt);
            }
        });
        jPanel5.add(rSButtonIconI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 250, 40));

        rSButtonIconI6.setBackground(new java.awt.Color(197, 30, 46));
        rSButtonIconI6.setForeground(new java.awt.Color(240, 240, 240));
        rSButtonIconI6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_home_80px.png"))); // NOI18N
        rSButtonIconI6.setText("Inicio                 ");
        rSButtonIconI6.setBorderPainted(false);
        rSButtonIconI6.setColorHover(new java.awt.Color(176, 23, 37));
        rSButtonIconI6.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        rSButtonIconI6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI6ActionPerformed(evt);
            }
        });
        jPanel5.add(rSButtonIconI6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 250, 40));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 590));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_angle_down_30px_2.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_sign_30px_1.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(574, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 650, 50));

        jpPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        jpPrincipal.setLayout(new javax.swing.BoxLayout(jpPrincipal, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(jpPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 650, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void rSButtonIconI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI1ActionPerformed
        // TODO add your handling code here:
//        new CambiaPanel(fondo, new paneles.OpcionSocio()); 
        OpcionSocio1 op= new OpcionSocio1(biblioteca);
        int width= jpPrincipal.getWidth();
        int height= jpPrincipal.getHeight();
        op.setSize(width, height);
        jpPrincipal.add(op);
        op.show();
    }//GEN-LAST:event_rSButtonIconI1ActionPerformed

    private void rSButtonIconI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI2ActionPerformed
        // TODO add your handling code here:
//        new CambiaPanel(fondo, new paneles.OpcionLibro());
        OpcionLibro1 op= new OpcionLibro1(biblioteca);
        int width= jpPrincipal.getWidth();
        int height= jpPrincipal.getHeight();
        op.setSize(width, height);
        jpPrincipal.add(op);
        op.show();
    }//GEN-LAST:event_rSButtonIconI2ActionPerformed

    private void rSButtonIconI6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI6ActionPerformed
        // TODO add your handling code here:
//        new CambiaPanel(fondo, new paneles.Inicio());
        Inicio1 inicio= new Inicio1(biblioteca);
        int width= jpPrincipal.getWidth();
        int height= jpPrincipal.getHeight();
        inicio.setSize(width, height);
        jpPrincipal.add(inicio);
        inicio.show();
    }//GEN-LAST:event_rSButtonIconI6ActionPerformed

    private void rSButtonIconI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI3ActionPerformed
        // TODO add your handling code here:
        
        OpcionListar inicio= new OpcionListar(biblioteca);
        int width= jpPrincipal.getWidth();
        int height= jpPrincipal.getHeight();
        inicio.setSize(width, height);
        jpPrincipal.add(inicio);
        inicio.show();
    }//GEN-LAST:event_rSButtonIconI3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rSButtonIconI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI4ActionPerformed
        OpcionPrestar inicio= new OpcionPrestar(biblioteca);
        int width= jpPrincipal.getWidth();
        int height= jpPrincipal.getHeight();
        inicio.setSize(width, height);
        jpPrincipal.add(inicio);
        inicio.show();
    }//GEN-LAST:event_rSButtonIconI4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JDesktopPane jpPrincipal;
    private rojerusan.RSButtonIconI rSButtonIconI1;
    private rojerusan.RSButtonIconI rSButtonIconI2;
    private rojerusan.RSButtonIconI rSButtonIconI3;
    private rojerusan.RSButtonIconI rSButtonIconI4;
    private rojerusan.RSButtonIconI rSButtonIconI6;
    // End of variables declaration//GEN-END:variables
}
